local gmod = dofile("tests/gmod.lua")
local passed, failed = 0, 0
local function eq(actual, expected, context)
    assert(actual == expected, (context or "values differ") .. ": expected " .. tostring(expected) .. ", got " .. tostring(actual))
end
local function test(name, callback)
    local ok, message=pcall(callback)
    if ok then passed=passed+1; print("PASS " .. name)
    else failed=failed+1; print("FAIL " .. name .. "\n  " .. tostring(message)) end
end

test("reject event starts without using an activator", function()
    local env=gmod.new(); local ply=env.ready()
    env.receive("SendNPCInformation", ply, "Raid")
    eq(#env.ents.FindByName("devonsSpawnedEntity"), 0)
    eq(#env.ents.FindByClass("activatorent"), 3)
end)
test("only the interacting player can start the event", function()
    local env=gmod.new(); local ply, ent=env.ready(); local stranger=env.entity("player")
    ent:AcceptInput("Use", ply, ply)
    env.receive("SendNPCInformation", stranger, "Raid")
    eq(env.totalEnemies, 0)
end)
test("valid interaction starts the configured event once", function()
    local env=gmod.new(); local ply, enemies=env.start()
    eq(#enemies, 5); eq(env.totalEnemies, 5); eq(#env.ents.FindByClass("activatorent"), 0)
    env.fire("OnNPCKilled", enemies[1], ply)
    env.receive("SendNPCInformation", ply, "Raid")
    eq(env.totalEnemies, 4, "a replay must not replace a killed enemy")
end)
for _, case in ipairs({"expired", "dead", "distant", "wrong event", "removed"}) do
    test("reject " .. case .. " interaction", function()
        local env=gmod.new(); local ply, ent=env.ready(); ent:AcceptInput("Use", ply, ply)
        local event="Raid"
        if case == "expired" then env.now=10000 elseif case == "dead" then ply.alive=false
        elseif case == "distant" then ply:SetPos(env.Vector(10000,0,0))
        elseif case == "wrong event" then event="Forged" elseif case == "removed" then ent:Remove() end
        env.receive("SendNPCInformation", ply, event)
        eq(env.totalEnemies, 0)
    end)
end
test("forged close cannot change another entity's movement", function()
    local env=gmod.new(); local ply, ent=env.ready(); local prop=env.entity("prop_physics")
    ent:AcceptInput("Use", ply, ply); env.receive("CloseInteractionMenu", ply, prop)
    eq(prop.moveChanges, nil)
    env.receive("CloseInteractionMenu", ply, {valid=false})
end)
test("closing an interaction cancels its start permission", function()
    local env=gmod.new(); local ply, ent=env.ready(); ent:AcceptInput("Use", ply, ply)
    env.receive("CloseInteractionMenu", ply, ent); env.receive("SendNPCInformation", ply, "Raid")
    eq(env.totalEnemies, 0)
end)
test("unrelated NPC kills cannot finish an idle event", function()
    local env=gmod.new(); env.fire("OnNPCKilled", env.entity("npc_zombie"), env.entity("worldspawn"))
    eq(env.messageCount("roundFinished"), 0)
end)
test("world kills count safely and finish exactly once", function()
    local env=gmod.new(); local ply, enemies=env.start(); local world=env.entity("worldspawn"); world.Nick=false
    for _, enemy in ipairs(enemies) do env.fire("OnNPCKilled", enemy, world) end
    eq(env.totalEnemies, 0); eq(env.messageCount("roundFinished"), 1)
    env.fire("OnNPCKilled", enemies[5], world)
    env.fire("OnNPCKilled", env.entity("npc_zombie"), world)
    eq(env.messageCount("roundFinished"), 1); eq(env.totalEnemies, 0)
    eq(env.timers.activatorSpawner.stopped, false)
end)
test("an entity with the same name cannot decrement the event", function()
    local env=gmod.new(); local ply=env.start(); local unrelated=env.entity("npc_zombie")
    unrelated:SetName("devonsSpawnedEntity"); env.fire("OnNPCKilled", unrelated, ply)
    eq(env.totalEnemies, 5)
end)
test("admin stop resets counts and permits another complete event", function()
    local env=gmod.new(); local ply=env.start(); ply.admin=true
    env.fire("PlayerSay", ply, "!stopEvent")
    eq(env.totalEnemies, 0); eq(#env.ents.FindByName("devonsSpawnedEntity"), 0)
    eq(env.messageCount("roundFinished"), 0); eq(env.messageCount("entitiesDeleted"), 1)
    local other, enemies=env.start(); eq(#enemies, 5)
    for _, enemy in ipairs(enemies) do env.fire("OnNPCKilled", enemy, other) end
    eq(env.messageCount("roundFinished"), 1)
end)
test("removing all event enemies unblocks spawning without a victory", function()
    local env=gmod.new(); local _, enemies=env.start()
    for _, enemy in ipairs(enemies) do enemy:Remove() end
    eq(env.totalEnemies, 0); eq(env.timers.activatorSpawner.stopped, false)
    eq(env.messageCount("roundFinished"), 0)
end)
test("missing enemy spawn keeps the activators available", function()
    local env=gmod.new(); local ply, ent=env.ready(); env.SpawnPositions[1].enemySpawnPositions={}
    ent:AcceptInput("Use", ply, ply); env.receive("SendNPCInformation", ply, "Raid")
    eq(env.totalEnemies, 0); eq(#env.ents.FindByClass("activatorent"), 3)
end)
test("invalid NPC class does not lock the spawner", function()
    local env=gmod.new(); env.failClass="npc_stalker"; env.start()
    eq(env.totalEnemies, 0); eq(env.timers.activatorSpawner.stopped, false)
end)
test("spawner respects the cap when activators already exist", function()
    local env=gmod.new(); env.npcInfo=env.returnNPCInformation("Raid")
    env.entity("activatorent"):Spawn(); env.fireTimer("activatorSpawner")
    eq(#env.ents.FindByClass("activatorent"), 3)
end)
test("manually spawned activators initialize before the first timer", function()
    local env=gmod.new(); local ent=env.entity("activatorent"); ent:Spawn()
    eq(ent:GetModel(), "models/alyx.mdl")
end)
test("missing and empty spawn maps safely return nil", function()
    local env=gmod.new()
    eq(env.returnSpawnPositions("unknown_map"), nil); eq(env.returnActivatorSpawns("unknown_map"), nil)
    env.SpawnPositions={ {map="gm_construct", enemySpawnPositions={}, activatorSpawnPositions={}} }
    eq(env.returnSpawnPositions("gm_construct"), nil); eq(env.returnActivatorSpawns("gm_construct"), nil)
    env.fireTimer("activatorSpawner"); eq(#env.ents.FindByClass("activatorent"), 0)
end)
test("sparse spawn lists choose an existing position", function()
    local env=gmod.new(); local point=env.Vector(1,2,3)
    env.SpawnPositions={ {map="gm_construct", enemySpawnPositions={[10]=point}, activatorSpawnPositions={[20]=point}} }
    for i=1,10 do eq(env.returnSpawnPositions("gm_construct"), point); eq(env.returnActivatorSpawns("gm_construct"), point) end
end)
test("an empty event config does not crash the spawner", function()
    local env=gmod.new(); env.NPCEdits={}; eq(env.determineRandomEvent(), nil)
    env.fireTimer("activatorSpawner"); eq(#env.ents.FindByClass("activatorent"), 0)
end)
for _, identifier in ipairs({"Ambush", "Supply Raid"}) do
    test("a custom event name drives the full configured encounter: " .. identifier, function()
        local env=gmod.new()
        env.NPCEdits[1].name=identifier
        local info=env.NPCEdits[1].information
        info.activatorModel="models/barney.mdl"
        info.npcPath="npc_zombie"
        info.maxNPCs=2
        info.dialogue="Synthetic custom encounter"
        local ply=env.entity("player")
        env.fireTimer("activatorSpawner")
        local activators=env.ents.FindByClass("activatorent")
        eq(#activators, 3, "custom definitions must not silently disable spawning")
        for _, ent in ipairs(activators) do
            eq(ent.EventIdentifier, identifier)
            eq(ent:GetModel(), info.activatorModel)
        end
        local ent=activators[1]
        ply:SetPos(ent:GetPos()); ent:AcceptInput("Use", ply, ply)
        local values=env.messages[1].values
        eq(values[3], identifier); eq(values[4], info.dialogue)
        local client=gmod.new(true)
        client.receive("OpenInteractionMenu", nil, values[1], values[2], values[3], values[4])
        client.panels[3]:DoClick()
        for _, message in ipairs(client.messages) do
            env.receive(message.name, ply, (table.unpack or unpack)(message.values))
        end
        local enemies=env.ents.FindByName("devonsSpawnedEntity")
        eq(#enemies, 2); eq(env.totalEnemies, 2)
        eq(#env.ents.FindByClass("activatorent"), 0)
        for _, enemy in ipairs(enemies) do
            eq(enemy:GetClass(), "npc_zombie")
            eq(enemy.health, env.returnEnemyHealth())
            env.fire("OnNPCKilled", enemy, ply)
        end
        eq(env.totalEnemies, 0); eq(env.messageCount("roundFinished"), 1)
        eq(env.timers.activatorSpawner.stopped, false)
        env.fireTimer("activatorSpawner")
        eq(#env.ents.FindByClass("activatorent"), 3)
    end)
end
test("the spawner accepts a custom event from a sparse definition list", function()
    local env=gmod.new(); local definition=env.NPCEdits[1]
    definition.name="Sparse Encounter"; env.NPCEdits={[7]=definition}
    env.entity("player"); env.fireTimer("activatorSpawner")
    local activators=env.ents.FindByClass("activatorent")
    eq(#activators, 3)
    for _, ent in ipairs(activators) do eq(ent.EventIdentifier, definition.name) end
end)
test("an unknown selected event cannot create unusable activators", function()
    local env=gmod.new(); env.entity("player")
    env.determineRandomEvent=function() return "Unknown" end
    env.fireTimer("activatorSpawner")
    eq(#env.ents.FindByClass("activatorent"), 0)
    eq(env.timers.activatorSpawner.stopped, false)
end)
for _, kind in ipairs({"Activator", "Enemy"}) do
    test("add " .. kind .. " spawn without duplicating an existing map", function()
        local env=gmod.new(); local admin=env.entity("player"); admin.admin=true
        table.insert(env.SpawnPositions, {map="other_map", enemySpawnPositions={}, activatorSpawnPositions={}})
        env.fire("PlayerSay", admin, "!set" .. kind .. "Spawn")
        eq(#env.SpawnPositions, 2); eq(#admin.chats, 1)
        eq(#env.SpawnPositions[1][kind == "Activator" and "activatorSpawnPositions" or "enemySpawnPositions"], 4)
    end)
    test("add " .. kind .. " spawn to an empty map config", function()
        local env=gmod.new(); local admin=env.entity("player"); admin.admin=true; env.SpawnPositions={}
        env.fire("PlayerSay", admin, "!set" .. kind .. "Spawn")
        eq(#env.SpawnPositions, 1); eq(#admin.chats, 1)
    end)
    test("remove the final " .. kind .. " spawn without errors or contradictory notices", function()
        local env=gmod.new(); local admin=env.entity("player"); admin.admin=true
        local key=kind == "Activator" and "activatorSpawnPositions" or "enemySpawnPositions"
        env.SpawnPositions[1][key]={env.Vector(0,0,0)}
        env.fire("PlayerSay", admin, "!remove" .. kind .. "Spawn")
        eq(#env.SpawnPositions[1][key], 0); eq(#admin.chats, 1)
        env.fire("PlayerSay", admin, "!remove" .. kind .. "Spawn"); eq(#admin.chats, 2)
    end)
end
test("client loads without accessing the server-only config", function()
    local env=gmod.new(true); assert(env.receivers.OpenInteractionMenu)
end)
local function menu(env)
    local ply=env.entity("player"); local ent=env.entity("activatorent"); ent.model="models/alyx.mdl"
    env.receive("OpenInteractionMenu", nil, ply, ent, "Raid", "Ready?")
    return env.panels[1], env.panels[3], env.panels[4], ent
end
test("client cancel closes the server interaction", function()
    local env=gmod.new(true); local frame, _, cancel, ent=menu(env); cancel:DoClick()
    eq(frame.valid, false); eq(env.messageCount("CloseInteractionMenu"), 1)
    eq(env.messages[1].values[1], ent)
end)
test("client start does not cancel its authorization first", function()
    local env=gmod.new(true); local frame, start=menu(env); start:DoClick()
    eq(frame.valid, false); eq(env.messageCount("SendNPCInformation"), 1)
    eq(env.messageCount("CloseInteractionMenu"), 0)
end)
test("client ignores an activator removed before the open message arrives", function()
    local env=gmod.new(true)
    env.receive("OpenInteractionMenu", nil, env.entity("player"), {valid=false}, "Raid", "Ready?")
    eq(#env.panels, 0)
end)
test("opening another menu closes the previous frame without cancelling the new interaction", function()
    local env=gmod.new(true); local frame, _, _, ent=menu(env)
    local ply=env.entity("player"); local nextEnt=env.entity("activatorent"); nextEnt.model="models/alyx.mdl"
    env.receive("OpenInteractionMenu", nil, ply, nextEnt, "Raid", "Ready again?")
    eq(frame.valid, false); eq(env.messageCount("CloseInteractionMenu"), 0)
end)
test("start button cannot submit the same menu twice", function()
    local env=gmod.new(true); local _, start=menu(env)
    start:DoClick(); start:DoClick()
    eq(env.messageCount("SendNPCInformation"), 1)
end)
test("the client start message completes a real server interaction", function()
    local server=gmod.new(); local ply, ent=server.ready(); ent:AcceptInput("Use", ply, ply)
    local client=gmod.new(true); local values=server.messages[1].values
    client.receive("OpenInteractionMenu", nil, values[1], values[2], values[3], values[4])
    client.panels[3]:DoClick()
    for _, message in ipairs(client.messages) do
        server.receive(message.name, ply, (table.unpack or unpack)(message.values))
    end
    eq(server.totalEnemies, 5)
end)
test("completion popup closes once after five seconds and leaves no repeating timer", function()
    local env=gmod.new(true); env.receive("roundFinished", nil)
    local frame=env.panels[1]; eq(frame.valid, true)
    eq(env.timers.destroyAlertFrame.delay, 5)
    eq(env.timers.destroyAlertFrame.repetitions, 1)
    env.fireTimer("destroyAlertFrame")
    eq(frame.valid, false); eq(env.panels[2].valid, false)
    eq(env.timers.destroyAlertFrame, nil)
end)
test("a new completion popup replaces the old frame and restarts its dismissal", function()
    local env=gmod.new(true); env.receive("roundFinished", nil)
    local first=env.panels[1]; local oldCallback=env.timers.destroyAlertFrame.callback
    env.receive("roundFinished", nil)
    local latest=env.panels[3]
    eq(first.valid, false); eq(env.panels[2].valid, false); eq(latest.valid, true)
    oldCallback() -- A stale callback must not remove the replacement.
    eq(latest.valid, true); assert(env.timers.destroyAlertFrame)
    env.fireTimer("destroyAlertFrame")
    eq(latest.valid, false); eq(env.timers.destroyAlertFrame, nil)
end)
test("completion cleanup tolerates an alert that was already closed", function()
    local env=gmod.new(true); env.receive("roundFinished", nil)
    env.panels[1]:Close()
    env.fireTimer("destroyAlertFrame")
    eq(env.timers.destroyAlertFrame, nil)
end)
test("completion cleanup leaves a separate interaction menu usable", function()
    local env=gmod.new(true); local frame, start=menu(env)
    env.receive("roundFinished", nil); env.fireTimer("destroyAlertFrame")
    eq(frame.valid, true); start:DoClick()
    eq(env.messageCount("SendNPCInformation"), 1)
    eq(env.messageCount("CloseInteractionMenu"), 0)
end)
test("death and respawn invalidate an earlier interaction", function()
    local env=gmod.new(); local ply, ent=env.ready(); ent:AcceptInput("Use", ply, ply)
    ply.alive=false; env.fire("PlayerDeath", ply); ply.alive=true
    env.receive("SendNPCInformation", ply, "Raid"); eq(env.totalEnemies, 0)
end)
test("spawn also clears permission after a silent death", function()
    local env=gmod.new(); local ply, ent=env.ready(); ent:AcceptInput("Use", ply, ply)
    env.fire("PlayerSpawn", ply)
    env.receive("SendNPCInformation", ply, "Raid"); eq(env.totalEnemies, 0)
end)
test("invalid callers cannot open the interaction", function()
    local env=gmod.new(); local ply, ent=env.ready()
    ent:AcceptInput("Use", nil, nil)
    ent:AcceptInput("Use", nil, {valid=false})
    ent:AcceptInput("Use", ply, env.entity("worldspawn"))
    eq(env.messageCount("OpenInteractionMenu"), 0)
end)
test("manually spawning with no event definitions removes the unusable activator", function()
    local env=gmod.new(); env.NPCEdits={}; local ent=env.entity("activatorent")
    ent:Spawn(); eq(ent.valid, false)
end)
test("non-admin stop cannot remove enemies or reset an event", function()
    local env=gmod.new(); local ply=env.start(); env.fire("PlayerSay", ply, "!stopEvent")
    eq(env.totalEnemies, 5); eq(#env.ents.FindByName("devonsSpawnedEntity"), 5)
    eq(env.messageCount("entitiesDeleted"), 0)
end)
test("an event partly removed by cleanup never claims all enemies were killed", function()
    local env=gmod.new(); local ply, enemies=env.start(); enemies[1]:Remove()
    for i=2,5 do env.fire("OnNPCKilled", enemies[i], ply) end
    eq(env.totalEnemies, 0); eq(env.messageCount("roundFinished"), 0)
    eq(env.timers.activatorSpawner.stopped, false)
    local nextPlayer, nextEnemies=env.start()
    for _, enemy in ipairs(nextEnemies) do env.fire("OnNPCKilled", enemy, nextPlayer) end
    eq(env.messageCount("roundFinished"), 1)
end)
test("manually spawning with missing event definitions removes the unusable activator", function()
    local env=gmod.new(); env.NPCEdits=nil; local ent=env.entity("activatorent")
    ent:Spawn(); eq(ent.valid, false)
end)
dofile("tests/persistence.lua")(gmod, test, eq)
dofile("tests/progress.lua")(gmod, test, eq)
dofile("tests/selection.lua")(gmod, test, eq)
dofile("tests/catalog.lua")(gmod, test, eq)
dofile("tests/readiness.lua")(gmod, test, eq)
dofile("tests/construction.lua")(gmod, test, eq)
dofile("tests/start-feedback.lua")(gmod, test, eq)
dofile("tests/dialogue-lifecycle.lua")(gmod, test, eq)
dofile("tests/spawn-edit-core.lua")(gmod, test, eq)
dofile("tests/spawn-edit-workflow.lua")(gmod, test, eq)
print(string.format("%d passed, %d failed", passed, failed))
os.exit(failed == 0 and 0 or 1)
